import React from "react";
import {Metadata} from "next";

export const metadata: Metadata = {
  title: {
    template: "%s | MP-4",
    default: "Home | MP-4",
  },
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  return (
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
  )
}